# DDRM Config
embedding_size: 64 # latent_dim_rec
lightGCN_n_layers: 3
keep_prob: 0.6
A_split: False
dropout: False
pretrain: 0
dropout_prob: 0
diff_lr: 0.0001
decay: 0.0001
epochs: 1000
batch_size: 2048
eval_step: 1
reweight: True
mean_type: 'x0'
steps: 100 # steps
noise_schedule: 'linear-var'
noise_scale: 0.0001 # noise_scale
noise_min: 0.0005
noise_max: 0.005
sampling_steps: 0
sampling_noise: False
beta_fixed: True
dims: [300]
act: 'tanh' # activation function for DNN
alpha: 0.1 # balance rec loss and reconstruct loss
beta: 0.1 # denoise data weight
drop_rate: 0.5
exponent: 1
num_gradual: 10000
weight_decay: 0.0001
learning_rate: 0.001
reg_weight: 0.0001 # reg for LightGCN
