# BPR 在 baby, sports, clothing, microlens 上的 reg_weight 为 0.1
embedding_size: 64
is_multimodal_model: False
reg_weight: 0.1 # [2.0, 1.0, 1e-01, 1e-02, 1e-03, 1e-04, 1e-05]
# hyper_parameters: ["reg_weight"]


